export const SCHOOL_ALIASES: Record<string, string> = {
  // North America - Ivy League
  'Harvard University': 'Harvard 哈佛',
  'Yale University': 'Yale 耶鲁',
  'Princeton University': 'Princeton 普林',
  'Columbia University': 'Columbia 哥大',
  'University of Pennsylvania': 'UPenn 宾大',
  'Cornell University': 'Cornell 康奈尔',
  'Brown University': 'Brown 布朗',
  'Dartmouth College': 'Dartmouth 达特茅斯',
  // North America - Top CS/EE
  'Massachusetts Institute of Technology': 'MIT 麻省理工',
  'Stanford University': 'Stanford 斯坦福',
  'Carnegie Mellon University': 'CMU 卡梅',
  'California Institute of Technology': 'Caltech 加州理工',
  'Georgia Institute of Technology': 'GaTech 佐治亚理工',
  'University of Illinois Urbana-Champaign': 'UIUC 伊利诺伊香槟',
  'University of Michigan, Ann Arbor': 'UMich 密歇根安娜堡',
  'University of Michigan': 'UMich 密歇根',
  'University of Texas at Austin': 'UT Austin 德州奥斯汀',
  'University of Washington': 'UW 华大西雅图',
  'University of Wisconsin-Madison': 'UW-Madison 威斯康星麦迪逊',
  // North America - UC System
  'University of California, Berkeley': 'UCB 伯克利',
  'University of California Berkeley': 'UCB 伯克利',
  'University of California, Los Angeles': 'UCLA 加州洛杉矶',
  'University of California, San Diego': 'UCSD 加州圣地亚哥',
  'University of California San Diego': 'UCSD 加州圣地亚哥',
  'University of California, Davis': 'UCD 加州戴维斯',
  'University of California, Irvine': 'UCI 加州尔湾',
  'University of California, Santa Barbara': 'UCSB 加州圣芭',
  'University of California, Santa Cruz': 'UCSC 加州圣克鲁兹',
  'University of California, Riverside': 'UCR 加州河滨',
  // North America - Other Top
  'University of Southern California': 'USC 南加大',
  'New York University': 'NYU 纽大',
  'Duke University': 'Duke 杜克',
  'Northwestern University': 'Northwestern 西北大学',
  'Johns Hopkins University': 'JHU 约翰霍普金斯',
  'Rice University': 'Rice 莱斯',
  'University of Chicago': 'UChicago 芝加哥',
  'Washington University in St. Louis': 'WashU 圣路易斯华盛顿',
  'University of Maryland, College Park': 'UMD 马里兰',
  'Purdue University': 'Purdue 普渡',
  'University of Minnesota, Twin Cities': 'UMN 明尼苏达',
  'Ohio State University': 'OSU 俄亥俄州立',
  'Pennsylvania State University': 'PSU 宾州州立',
  'University of Florida': 'UF 佛罗里达',
  'University of North Carolina at Chapel Hill': 'UNC 北卡教堂山',
  'Virginia Tech': 'VT 弗吉尼亚理工',
  'University of Virginia': 'UVA 弗吉尼亚',
  'Boston University': 'BU 波士顿大学',
  'Northeastern University': 'NEU 东北大学',
  'University of Massachusetts Amherst': 'UMass 麻省大学',
  'Stony Brook University': 'SBU 石溪',
  'Rutgers University': 'Rutgers 罗格斯',
  'University of Pittsburgh': 'UPitt 匹兹堡',
  'University of Colorado Boulder': 'CU Boulder 科罗拉多博尔德',
  'Arizona State University': 'ASU 亚利桑那州立',
  'Texas A&M University': 'TAMU 德州农工',
  'Emory University': 'Emory 埃默里',
  'Vanderbilt University': 'Vanderbilt 范德堡',
  // Canada
  'University of Toronto': 'UofT 多大',
  'University of British Columbia': 'UBC 英属哥伦比亚',
  'McGill University': 'McGill 麦吉尔',
  'University of Waterloo': 'UWaterloo 滑铁卢',
  'University of Alberta': 'UAlberta 阿尔伯塔',
  'Simon Fraser University': 'SFU 西蒙弗雷泽',
  'McMaster University': 'McMaster 麦克马斯特',
  // UK
  'University of Oxford': 'Oxford 牛津',
  'University of Cambridge': 'Cambridge 剑桥',
  'Imperial College London': 'IC 帝国理工',
  'University College London': 'UCL 伦敦大学学院',
  'University of Edinburgh': 'Edinburgh 爱丁堡',
  'University of Manchester': 'Manchester 曼大',
  "King's College London": 'KCL 伦敦国王学院',
  'University of Warwick': 'Warwick 华威',
  'University of Bristol': 'Bristol 布里斯托',
  'University of Glasgow': 'Glasgow 格拉斯哥',
  'University of Leeds': 'Leeds 利兹',
  'University of Southampton': 'Southampton 南安普顿',
  'University of Bath': 'Bath 巴斯',
  'London School of Economics and Political Science': 'LSE 伦敦政经',
  'University of Birmingham': 'Birmingham 伯明翰',
  'University of Sheffield': 'Sheffield 谢菲尔德',
  'University of Nottingham': 'Nottingham 诺丁汉',
  'Durham University': 'Durham 杜伦',
  // Europe
  'ETH Zurich': 'ETH ETHz 苏黎世联邦理工',
  EPFL: 'EPFL 洛桑联邦理工',
  'Technical University of Munich': 'TUM 慕尼黑工大',
  'Delft University of Technology': 'TU Delft 代尔夫特理工',
  'KTH Royal Institute of Technology': 'KTH 皇家理工',
  'Aalto University': 'Aalto 阿尔托',
  'Technical University of Berlin': 'TU Berlin 柏林工大',
  'University of Amsterdam': 'UvA 阿姆斯特丹大学',
  'Politecnico di Milano': 'PoliMi 米兰理工',
  'Ludwig Maximilian University of Munich': 'LMU 慕尼黑大学',
  'RWTH Aachen University': 'RWTH 亚琛工大',
  'Karlsruhe Institute of Technology': 'KIT 卡尔斯鲁厄理工',
  'Eindhoven University of Technology': 'TU/e 埃因霍温理工',
  // Hong Kong
  'The University of Hong Kong': 'HKU 港大',
  'The Chinese University of Hong Kong': 'CUHK 港中文 中大',
  'The Hong Kong University of Science and Technology': 'HKUST 港科大',
  'Hong Kong University of Science and Technology': 'HKUST 港科大 港科',
  'City University of Hong Kong': 'CityU 城大',
  'The Hong Kong Polytechnic University': 'PolyU 理大',
  'Hong Kong Polytechnic University': 'PolyU 理大',
  'Hong Kong Baptist University': 'HKBU 浸会',
  // Singapore
  'National University of Singapore': 'NUS 新国立',
  'Nanyang Technological University': 'NTU 南洋理工',
  'Singapore Management University': 'SMU 新加坡管理大学',
  // Japan
  'The University of Tokyo': 'UTokyo 东大',
  'Kyoto University': 'Kyoto 京大',
  'Tokyo Institute of Technology': 'Tokyo Tech 东工大',
  'Osaka University': 'Osaka 阪大',
  'Tohoku University': 'Tohoku 东北大',
  // South Korea
  'Seoul National University': 'SNU 首尔国立',
  'Korea Advanced Institute of Science and Technology': 'KAIST 韩科院',
  KAIST: 'KAIST 韩科院',
  'Pohang University of Science and Technology': 'POSTECH 浦项科技',
  'Yonsei University': 'Yonsei 延世',
  'Korea University': 'KU 高丽大学',
  // Australia
  'The University of Melbourne': 'Melbourne 墨尔本大学',
  'University of Melbourne': 'Melbourne 墨尔本大学',
  'The University of Sydney': 'Sydney 悉尼大学',
  'University of Sydney': 'Sydney 悉尼大学',
  'University of New South Wales': 'UNSW 新南威尔士',
  'Australian National University': 'ANU 澳国立',
  'The University of Queensland': 'UQ 昆士兰大学',
  'Monash University': 'Monash 莫纳什',
  'The University of Adelaide': 'Adelaide 阿德莱德',
  'The University of Western Australia': 'UWA 西澳大学',
  // Macau
  'University of Macau': 'UM 澳门大学',
  'Macau University of Science and Technology': 'MUST 澳科大',
};
export function getSchoolShortName(school: string): string {
  const aliases = SCHOOL_ALIASES[school];
  if (!aliases) return school;
  const abbr = aliases.split(' ')[0];
  return abbr || school;
}

export function getSchoolAliases(school: string): string {
  return SCHOOL_ALIASES[school] || '';
}

export function schoolAbbr(school: string): string | null {
  const short = getSchoolShortName(school);
  return short === school ? null : short;
}
