version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: swifts-nest-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: swifts_nest
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

    
volumes:
  postgres_data: